name: vnlunar
description: A package that helps convert Vietnamese Lunar Calendar to Solar and vice versa.
version: 1.1.1
repository: https://github.com/nguyen703/vnlunar

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
